language: node_js
node_js:
  - "stable"
services:
  - postgresql
install:
  - npm install
before_script:
  - cp .env.travis .env
  - psql -c "DROP DATABASE IF EXISTS travis;" -U postgres
  - psql -c "CREATE DATABASE travis;" -U postgres
cache:
  directories:
    - node_modules
script:
  - npm run test:travis
after_success:
  - npm run coverage